### ISSUE TITLE
JsonMappingExceptions due to missing type ids: DEVICE_ADDED, DEVICE_REMOVED, DEVICE_UPDATED

### ISSUE THREAD

**Issue by wborn** [vitalidze/chromecast-java-api-v2#103]
When using a Chromecast audio group JsonMappingExceptions are logged due to several missing type ids.

## DEVICE_ADDED

Reproducible by:
1. Start some music on a Chromecast audio group
2. Cycle power of one of the Chromecasts part of the group
3. When the powered off Chromecast resumes playback the DEVICE_ADDED response is received

Example stack trace:

```
2018-08-01 10:48:23.057 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling
org.codehaus.jackson.map.JsonMappingException: Could not resolve type id 'DEVICE_ADDED' into a subtype of [simple type, class su.litvak.chromecast.api.v2.StandardResponse]
	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownTypeException(StdDeserializationContext.java:273) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:117) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:74) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:89) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.StdDeserializerProvider$WrappedDeserializer.deserialize(StdDeserializerProvider.java:494) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1990) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.EventListenerHolder.deliverEvent(EventListenerHolder.java:56) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel.notifyListenersOfSpontaneousEvent(Channel.java:440) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel.access$600(Channel.java:50) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:186) [227:org.openhab.binding.chromecast:2.3.0]
```

See also: https://github.com/openhab/openhab2-addons/issues/3719

---

## DEVICE_REMOVED

Reproducible by:
1. Start some music on a Chromecast audio group
2. Cycle power of one of the Chromecast part of the group
3. When it is detected the powered off Chromecast is no longer part of the group the DEVICE_REMOVED response is received

Example stack trace:

```
2018-08-01 10:48:10.100 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling
org.codehaus.jackson.map.JsonMappingException: Could not resolve type id 'DEVICE_REMOVED' into a subtype of [simple type, class su.litvak.chromecast.api.v2.StandardResponse]
	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownTypeException(StdDeserializationContext.java:273) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:117) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:74) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:89) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.StdDeserializerProvider$WrappedDeserializer.deserialize(StdDeserializerProvider.java:494) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1990) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.EventListenerHolder.deliverEvent(EventListenerHolder.java:56) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel.notifyListenersOfSpontaneousEvent(Channel.java:440) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel.access$600(Channel.java:50) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:186) [227:org.openhab.binding.chromecast:2.3.0]
```

---

## DEVICE_UPDATED

Reproducible by:
1. Start some music on a Chromecast audio group
2. Change volume of the group with the Google Home App

```
2018-08-03 17:35:13.670 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling
org.codehaus.jackson.map.JsonMappingException: Could not resolve type id 'DEVICE_UPDATED' into a subtype of [simple type, class su.litvak.chromecast.api.v2.StandardResponse]
	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownTypeException(StdDeserializationContext.java:273) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:117) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:74) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:89) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.deser.StdDeserializerProvider$WrappedDeserializer.deserialize(StdDeserializerProvider.java:494) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695) [227:org.openhab.binding.chromecast:2.3.0]
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1990) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.EventListenerHolder.deliverEvent(EventListenerHolder.java:56) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel.notifyListenersOfSpontaneousEvent(Channel.java:440) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel.access$600(Channel.java:50) [227:org.openhab.binding.chromecast:2.3.0]
	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:186) [227:org.openhab.binding.chromecast:2.3.0]
```

See also: https://github.com/openhab/openhab2-addons/issues/3729

--- 

Looks like the api should either ignore these messages or add them to the JsonSubTypes in StandardResponse:

https://github.com/vitalidze/chromecast-java-api-v2/blob/51463406eb86efbd246d5483364af9db7dcec773/src/main/java/su/litvak/chromecast/api/v2/StandardResponse.java#L28-L36

**Comment by vitalidze** [comment]
Thank you for sending these. I agree that it must be added, but we need response examples to create a java class for mapping the response. Unfortunately I don't have the Chromecast Audio and I suppose I won't be able to reproduce it myself. So, please enable the DEBUG logging and add here the JSON messages that are received with such types. Then, we can add them along with unit tests.

**Comment by wborn** [comment]
I've edited my first comment so the logging also contains the debug logging with the JSON message @vitalidze . Would be great to have this fixed! :-)

**Comment by vitalidze** [comment]
Thank you very much for providing detailed specification. I have made necessary changes in code. Can you please check whether it works in SNAPSHOT version of the library? If it works for you, then I will add unit tests and then if #104 is working too, I will release a new version.

**Comment by wborn** [comment]
Excellent! All these exceptions are gone after retesting the scenarios with a local build containing the latest master. :smile: :1st_place_medal:

**Comment by wborn** [comment]
Thanks a lot @vitalidze! :+1:
