### ISSUE TITLE
NullPointerException in setDestinationId(..) when starting to cast

### ISSUE THREAD

**Issue by wborn** [vitalidze/chromecast-java-api-v2#104]
While starting to cast some audio to a Chromecast Audio the following NPE occured:

```
18:55:33.357 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  --> {"type":"GET_STATUS","requestId":5409}
18:55:33.392 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  <-- {"requestId":5409,"status":{"applications":[{"appId":"705D30C6","displayName":"Google Play Music","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"b7e3cd51-d4fb-4d51-86a3-aadad8fa8a0b","statusText":"Google Play Music","transportId":"b7e3cd51-d4fb-4d51-86a3-aadad8fa8a0b"}],"userEq":{"high_shelf":{"frequency":4500.0,"gain_db":0.0,"quality":0.707},"low_shelf":{"frequency":150.0,"gain_db":0.0,"quality":0.707},"max_peaking_eqs":0,"peaking_eqs":[]},"volume":{"controlType":"master","level":0.1529465764760971,"muted":false,"stepInterval":0.019999999552965164}},"type":"RECEIVER_STATUS"}
18:55:33.395 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  --> {"type":"GET_STATUS","requestId":5410}
18:55:33.438 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  <-- {"requestId":5410,"status":{"applications":[{"appId":"705D30C6","displayName":"Google Play Music","isIdleScreen":false,"launchedFromCloud":false,"namespaces":[{"name":"urn:x-cast:com.google.cast.media"}],"sessionId":"b7e3cd51-d4fb-4d51-86a3-aadad8fa8a0b","statusText":"Google Play Music","transportId":"b7e3cd51-d4fb-4d51-86a3-aadad8fa8a0b"}],"userEq":{"high_shelf":{"frequency":4500.0,"gain_db":0.0,"quality":0.707},"low_shelf":{"frequency":150.0,"gain_db":0.0,"quality":0.707},"max_peaking_eqs":0,"peaking_eqs":[]},"volume":{"controlType":"master","level":0.1529465764760971,"muted":false,"stepInterval":0.019999999552965164}},"type":"RECEIVER_STATUS"}
18:55:33.439 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  --> {"type":"CONNECT","origin":{}}
18:55:33.440 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  --> {"type":"GET_STATUS","requestId":5411}
18:55:33.483 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  <-- {"requestId":5411,"status":[],"type":"MEDIA_STATUS"}
18:55:34.723 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  --> {"type":"PING"}
18:55:34.762 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  <-- {"type":"PONG"}
18:55:35.139 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  --> {"type":"PING"}
18:55:35.175 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  <-- {"type":"PONG"}
18:55:35.818 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  --> {"type":"GET_STATUS","requestId":264}
18:55:35.857 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  <-- {"requestId":264,"status":{"applications":[{"appId":"531A4F84","displayName":"Google Play Music","isIdleScreen":false,"launchedFromCloud":false,"sessionId":"a8d7b430-4cef-4bc3-9e4e-a82c725aab74","statusText":"Google Play Music"}],"userEq":{"high_shelf":{"frequency":4500.0,"gain_db":0.0,"quality":0.707},"low_shelf":{"frequency":150.0,"gain_db":0.0,"quality":0.707},"max_peaking_eqs":0,"peaking_eqs":[]},"volume":{"controlType":"master","level":0.2432800680398941,"muted":false,"stepInterval":0.019999999552965164}},"type":"RECEIVER_STATUS"}
18:55:35.858 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  --> {"type":"GET_STATUS","requestId":265}
18:55:35.896 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  <-- {"requestId":265,"status":{"applications":[{"appId":"531A4F84","displayName":"Google Play Music","isIdleScreen":false,"launchedFromCloud":false,"sessionId":"a8d7b430-4cef-4bc3-9e4e-a82c725aab74","statusText":"Google Play Music"}],"userEq":{"high_shelf":{"frequency":4500.0,"gain_db":0.0,"quality":0.707},"low_shelf":{"frequency":150.0,"gain_db":0.0,"quality":0.707},"max_peaking_eqs":0,"peaking_eqs":[]},"volume":{"controlType":"master","level":0.2432800680398941,"muted":false,"stepInterval":0.019999999552965164}},"type":"RECEIVER_STATUS"}
18:55:35.899 [DEBUG] [su.litvak.chromecast.api.v2.Channel  ] -  --> {"type":"CONNECT","origin":{}}
18:55:35.899 [WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception
java.lang.NullPointerException: null
	at su.litvak.chromecast.api.v2.CastChannel$CastMessage$Builder.setDestinationId(CastChannel.java:1358) [227:org.openhab.binding.chromecast:2.4.0.201808221411]
	at su.litvak.chromecast.api.v2.Channel.write(Channel.java:404) [227:org.openhab.binding.chromecast:2.4.0.201808221411]
	at su.litvak.chromecast.api.v2.Channel.write(Channel.java:396) [227:org.openhab.binding.chromecast:2.4.0.201808221411]
	at su.litvak.chromecast.api.v2.Channel.startSession(Channel.java:484) [227:org.openhab.binding.chromecast:2.4.0.201808221411]
	at su.litvak.chromecast.api.v2.Channel.getMediaStatus(Channel.java:519) [227:org.openhab.binding.chromecast:2.4.0.201808221411]
	at su.litvak.chromecast.api.v2.ChromeCast.getMediaStatus(ChromeCast.java:329) [227:org.openhab.binding.chromecast:2.4.0.201808221411]
	at org.openhab.binding.chromecast.internal.ChromecastCommander.handleRefresh(ChromecastCommander.java:105) [227:org.openhab.binding.chromecast:2.4.0.201808221411]
	at org.openhab.binding.chromecast.handler.ChromecastHandler$Coordinator$1.run(ChromecastHandler.java:228) [227:org.openhab.binding.chromecast:2.4.0.201808221411]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

After checking the code of the stack trace I think `runningApp.transportId` was null resulting in this NPE:

https://github.com/vitalidze/chromecast-java-api-v2/blob/51463406eb86efbd246d5483364af9db7dcec773/src/main/java/su/litvak/chromecast/api/v2/ChromeCast.java#L324-L330

**Comment by vitalidze** [comment]
The `getMediaStatus` cannot work without transportId (or session id). Please send debug messages for investigation. To do that please enable the DEBUG level. It will be showing messages sent/received in JSON format.

**Comment by wborn** [comment]
I've updated my first comment so it includes several seconds of logging @vitalidze. 
This is probably the logging of communications with a few Chromecast Audios.

**Comment by vitalidze** [comment]
I have fixed this in code. Can you please build the SNAPSHOT and check whether it worked or not?

**Comment by wborn** [comment]
Thanks! I've made a local build of the latest master and the NPE no longer occurs. :-)

**Comment by vitalidze** [comment]
The new version is being released right now. I hope it will become available in Maven Central tomorrow. Thank you very much for your cooperation and patience :)
