### ISSUE TITLE
JsonMappingException due to "TIME_TICK" type undefined

### ISSUE THREAD

**Issue by bkpsu** [vitalidze/chromecast-java-api-v2#106]
Similar to #103 - I'm seeing a constant exception (1 second period) when playing a Pandora stream on my Chromecast Audio. The exception is as follows:

`
2018-12-23 08:01:15.070 [WARN ] [su.litvak.chromecast.api.v2.Channel ] - Error while handling

org.codehaus.jackson.map.JsonMappingException: Could not resolve type id 'TIME_TICK' into a subtype of [simple type, class su.litvak.chromecast.api.v2.StandardResponse]

 at [Source: N/A; line: -1, column: -1]

	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownTypeException(StdDeserializationContext.java:273) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:117) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:74) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:89) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.deser.StdDeserializerProvider$WrappedDeserializer.deserialize(StdDeserializerProvider.java:494) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1990) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at su.litvak.chromecast.api.v2.EventListenerHolder.deliverEvent(EventListenerHolder.java:56) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at su.litvak.chromecast.api.v2.Channel.notifyListenersOfSpontaneousEvent(Channel.java:452) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at su.litvak.chromecast.api.v2.Channel.access$600(Channel.java:51) ~[239:org.openhab.binding.chromecast:2.5.0.201812170851]

	at su.litvak.chromecast.api.v2.Channel$ReadThread.run(Channel.java:195) [239:org.openhab.binding.chromecast:2.5.0.201812170851]`

Steps to reproduce:

1. Start Pandora stream
2. Witness exceptions with 1 second period (I'm using openHAB logs to see the exception)
3. Pause stream
4. Exceptions stop (they restart when the stream is restarted)

**Comment by vitalidze** [comment]
Please include output of the DEBUG log. I need to see the incoming message in JSON format.

**Comment by bkpsu** [comment]
AS requested, the JSON packet in the DEBUG log:

`{"requestId":0,"type":"TIME_TICK","timeElapsed":142,"timeRemaining":73,"track":"TR:2740060"}`

**Comment by vitalidze** [comment]
Thank you. I have just fixed this issue and added unit test. It will be included into next release.

**Comment by vitalidze** [comment]
I have just released version `0.10.6` containing this fix. Hopefully it will be available in 24h (usually faster). Please open a new ticket if problem remains.
