### ISSUE TITLE
getting INVALID_COMMAND

### ISSUE THREAD

**Issue by yogaredhat** [vitalidze/chromecast-java-api-v2#129]
I was able to connect to device successfully. I tried pause and is working fine but when I try to use load function as describe in readme , its giving me this error.

su.litvak.chromecast.api.v2.ChromeCastException: Invalid request: INVALID_COMMAND
	at su.litvak.chromecast.api.v2.Channel.send(Channel.java:388)
	at su.litvak.chromecast.api.v2.Channel.sendStandard(Channel.java:348)
	at su.litvak.chromecast.api.v2.Channel.load(Channel.java:505)
	at su.litvak.chromecast.api.v2.ChromeCast.load(ChromeCast.java:448)

**Comment by grolschie** [comment]
Maybe provide more detail about your use of the load function? Some code?
