### ISSUE TITLE
hi   can someone help with this error 

### ISSUE THREAD

**Issue by janoz73** [vitalidze/chromecast-java-api-v2#22]
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at su.litvak.chromecast.api.v2.Channel.<clinit>(Channel.java:45)
	at su.litvak.chromecast.api.v2.ChromeCast.connect(ChromeCast.java:92)
	at com.mycompany.mavenproject1.FXMLController.handleButtonAction(FXMLController.java:37)
	... 60 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 63 more

after chromecast was found i try to connect to it but   then this error will show up.  :-(

greets

janoz

**Comment by vitalidze** [comment]
Looks like you are missing the slf4j library on your classpath. Or you have an incompatible version of that library.

**Comment by janoz73** [comment]
thanks for your reply    i solved the problem.....

now ive problems with this error..   **Caused by: su.litvak.chromecast.api.v2.ChromeCastException: Application launch error: NOT_FOUND
**
after            Application app = chromecast.launchApp("APP_ID");

maby you canhelp me with that..    greets  janoz

**Comment by vitalidze** [comment]
You should put valid identifier of your application instead of `APP_ID`.

**Comment by janoz73** [comment]
ok thanks...    that works for me    
no i have third problem...  maby you can help me also with that...

error
 Caused by: su.litvak.chromecast.api.v2.ChromeCastException: ChromeCast has invalid state to resume media playback

how to solve this problem :-)             greets   janoz

**Comment by vitalidze** [comment]
I guess you should read the text of error message. It clearly states that your device is in such state, when you cannot resume media playback. Most probably it does not play anything at the moment.

**Comment by janoz73** [comment]
hi  again  :-) no errors now :-)   
i see some activity on my tv now.  it turns  black and afters seconds it goes to the main screen.
what do i wrong.?.     ill hope you can help me with perhaps this last step..  :-)

**Comment by vitalidze** [comment]
I have no idea. I think you need to read something about chromecast applications to understand which steps you need to perform to make it working. I think this should be a good place to start: https://developers.google.com/cast/docs/developers

**Comment by janoz73** [comment]
thanks ...   i will take a look      thanks  for your help.    greets

**Comment by vitalidze** [comment]
Any update on this issue? May I close it?
