### ISSUE TITLE
When connecting to any valid device, java.lang fails

### ISSUE THREAD

**Issue by kamenomagic** [vitalidze/chromecast-java-api-v2#82]
When specifying a port of the chromecast or when successfully finding a device and trying to connect to it, the code throws a java.lang error:
```
Exception in thread "Thread-25" java.lang.VerifyError: class su.litvak.chromecast.api.v2.CastChannel$DeviceAuthMessage overrides final method isInitialized.()Z
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at su.litvak.chromecast.api.v2.Channel.connect(Channel.java:279)
	at su.litvak.chromecast.api.v2.Channel.open(Channel.java:262)
	at su.litvak.chromecast.api.v2.ChromeCast.connect(ChromeCast.java:113)
```

Tried both
```
...
    chromecast = new ChromeCast(ip);
    chromecast.connect();
```
and
```
      ChromeCasts.startDiscovery();
      while(true) {
        Optional<ChromeCast> found = ChromeCasts.get().stream().filter(chromeCast -> chromeCast.getTitle().equals(name)).findFirst();
        if(found.isPresent()) {
          chromecast = found.get();
          break;
        }
      }
      chromecast.connect();
```

**Comment by kamenomagic** [comment]
https://stackoverflow.com/questions/100107/causes-of-getting-a-java-lang-verifyerror

**Comment by kamenomagic** [comment]
This was a classpath issue on my part
