### ISSUE TITLE
.load() and .getStatus() hang

### ISSUE THREAD

**Issue by deontologic** [vitalidze/chromecast-java-api-v2#92]
Hello; the below snippet works great:
```java
public class Main {

    public static void main(String[] args) throws IOException, InterruptedException {
        ChromeCasts.startDiscovery(InetAddress.getLocalHost());

        ChromeCasts.registerListener(new ChromeCastsListener() {
            @Override
            public void newChromeCastDiscovered(ChromeCast chromeCast) {
                System.out.println(chromeCast.getName());
            }

            @Override
            public void chromeCastRemoved(ChromeCast chromeCast) {
            }
        });
    }
}
```
But replacing the getName() call with getStatus() or trying to load + play media causes the application to hang. I should note that printing every device name outputs strings like "Chromecast-2342342kj234kj5435345kj" and "GoogleHome-34345jkjk435345345j345", while using chrome's built in cast feature shows human-readable names. There are multiple chromecasts, google home devices, and the cast speakers on my network. I've tried this on different mac and windows without luck.

**Comment by vitalidze** [comment]
1) This means your chromecast device does not respond to the request. Can you try enable debug level of logging to see low-level messages during the conversation of your app with chromecast device?

2) This is the name, which is received during device discovery. I doubt anything can be done here, but the human-readable name should be somewhere in `ChromeCast` object too.

**Comment by deontologic** [comment]
No additional info from debug logging, but I wrapped in future w/ timeout of 3 seconds:
```
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at swagcast.Main$1.newChromeCastDiscovered(Main.java:29)
	at su.litvak.chromecast.api.v2.ChromeCasts$MyServiceListener.serviceAdded(ChromeCasts.java:59)
	at javax.jmdns.impl.ListenerStatus$ServiceListenerStatus.serviceAdded(ListenerStatus.java:60)
	at javax.jmdns.impl.JmDNSImpl$4.run(JmDNSImpl.java:1290)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by vitalidze** [comment]
Well, this stack trace does not show anything from internal chromecast-api classes. Maybe you can create a thread dump or something like this to see where your method invocation hangs?

**Comment by deontologic** [comment]
I profiled w/ VisualVM, and hanging occurs on clearing the dns cache.

Probably not an issue with this library it seems.. I'll take a look at jmDNS

**Comment by vitalidze** [comment]
Closed due to inactivity.
